# Generated by Django 3.0.3 on 2020-03-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistant',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
