# Generated by Django 3.0.3 on 2020-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
