# Generated by Django 3.0.3 on 2020-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200319_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fullname',
            field=models.CharField(default='Deathcrush', max_length=50),
            preserve_default=False,
        ),
    ]
