# Generated by Django 3.0.3 on 2020-03-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200306_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
    ]
