# Generated by Django 3.0.3 on 2020-03-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='docid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor', unique=True),
        ),
    ]
