# Generated by Django 3.0.3 on 2020-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200320_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='notifications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
