# Generated by Django 3.0.3 on 2020-03-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20200306_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Assistant')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor', unique=True)),
                ('patid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient', unique=True)),
            ],
        ),
    ]
