# Generated by Django 3.0.3 on 2020-03-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
