# Generated by Django 3.0.3 on 2020-03-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20200306_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='docid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
